yes ,

try{
}
catch(DivideByZeroException e)
{
}
catch(ArrayOutOfBoundException e)
{
}
catch(Exception e)
{
}